### ISSUE TITLE
Add equations to appointment.methods docstrings

### ISSUE THREAD

**Issue by andrewtavis** [andrewtavis/poli-sci-kit#19]
Equations should be added to the doc strings of `largest_remainder` and `highest_average` in [poli_sci_kit.appointment.methods](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/methods.py). They would then be rendered in the documentation for greater clarity.

Most of these equations can be found on the Wikipedia pages for the respective methods. They should be placed in the options section of the `quota_style` and `averaging_style` parameters respectively.

**Comment by Ajay-Singh-Rana** [comment]
Hey... you have already added the equations to the documentation...What else must be done..?

**Comment by andrewtavis** [comment]
Thank you for writing. I was thinking of changing them over to LaTeX so that they're in the actual equation forms in the documentation. Do you think that it's enough as it is right now - i.e. does it make enough sense?

**Comment by Ajay-Singh-Rana** [comment]
Hey...Yes, it does make enough sense the way these are described as of now but if you wanna add LaTex to it you might want to learn about Sphinx documentation tool.I would like to help with it. I too haven't learnt much about it but i'll look at the documentation for that tool sooner.

**Comment by andrewtavis** [comment]
Thanks again for writing :) I think that it should be able to work with the current Sphinx and NumPy docs setup for the documentation. Let me try to convert one of the equations over to LateX, see how it looks (maybe maintaining the current equations that would explain what the symbols would be), and then I'll write back and see what you think. I forgot to mention [appointment.metrics](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/metrics.py) in the issue, but that's another part of the package that as of now has no equation documentation.

Very much appreciate the dialogue on this :)

**Comment by andrewtavis** [comment]
@Ajay-Singh-Rana, I just finished figuring out how to make all this work, with a comparison of how it looks in the documentation being [here](https://poli-sci-kit.readthedocs.io/en/latest/appointment/methods.html) (see `largest_remainder` vs. `highest_average`). It makes the equations harder to read [in the code](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/methods.py), but dramatically easier to read in the documentation, so I guess I would prefer it over the current version :)

The following is an explanation for you, and you'd be more than welcome to do the equations for `highest_averages` in [appointment.methods](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/methods.py) as well as any functions in [appointment.metrics](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/metrics.py):

1. In [conf.py](https://github.com/andrewtavis/poli-sci-kit/blob/main/docs/source/conf.py) of the documentation you need the extension `sphinx.ext.imgmath`, which allows equations to be rendered to pngs (this has now been added to poli-sci-kit's `conf.py`)
2. If you want to add an equation, then the as seen in the new docstring for [appointment.methods.largest_remaindeer](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/methods.py) you add the following:

```
.. math::
    Latex you want rendered
```

3. The docstring also needs to be converted to an [r-sting](https://stackoverflow.com/questions/2081640/what-exactly-do-u-and-r-string-flags-do-and-what-are-raw-string-literals) (this is now the case for `largest_remainder` but not `highest_averages`)
4. You also need to use `&=` instead of `=` in equations

If you do want to do a pull request that converts equations over to LaTeX for poli-sci-kit's documentation, you could use [the following LaTeX editor](https://latex.codecogs.com/eqneditor/editor.php) to test your equations and then add them to the docstrings (remembering `&=` instead of `=`). I would be more than happy to help if one of the equations doesn't make sense, or if getting the LaTeX to work is a bit confusing (not sure whether you've used it before). 

Hope you're having a nice day :)

**Comment by andrewtavis** [comment]
The most recent commits finished the docstring equations for [poli_sci_kit.appointment.methods](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/methods.py), and I've made #25 for the equations for [poli_sci_kit.appointment.metrics](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/appointment/metrics.py). Closing this one now :)
