### ISSUE TITLE
Accurate semicircle parliament plot allocations

### ISSUE THREAD

**Issue by andrewtavis** [andrewtavis/poli-sci-kit#20]
The semicircle version of the [parliament plot](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/plot/parliament.py) at times doesn't put all the seats for a group in the same area. There is potentially a better method of allocating the scatterplot points in that function, or break points could be put in given parliament sizes to assure that groups have all their seats in one area of the plot.

Fixes for this would specifically need to target [poli_sci_kit.utils.gen_parl_points](https://github.com/andrewtavis/poli-sci-kit/blob/main/src/poli_sci_kit/utils.py).

**Comment by gnegrelli** [comment]
Is there any test data that I can use to see this behaviour and work on a solution?

**Comment by andrewtavis** [comment]
Hey @gnegrelli 👋 I'd say the best thing to do would be to play around with the [plot.ipynb](https://github.com/andrewtavis/poli-sci-kit/blob/main/examples/plot.ipynb) notebook and you can make up your own allocations to test if it's all working :)

**Comment by gnegrelli** [comment]
@andrewtavis, thanks for the tip. I created my own allocation (based on a project I was working on) and got the plot below using the original code for scatterplot point allocation.
![image](https://github.com/andrewtavis/poli-sci-kit/assets/44068014/b48f0668-1d8e-442e-871f-2cb1a46797e1)

I then tried to group the points based on the angle between them and the origin (0,0), resulting in the following plot.
![image](https://github.com/andrewtavis/poli-sci-kit/assets/44068014/6534d3b2-7d7e-478f-8ecf-03e026cf25e2)

This seems to work fine for the larger groups, but it gets messy for groups with only a few seats, as we can see on the right hand side of the plot.

**Comment by andrewtavis** [comment]
Seems better for sure though, @gnegrelli! I'd accept a PR for the current implementation, but if you want to experiment a bit more then by all means! In a PR I might be able to play around a bit to see if we could figure out the last irregularities though :)

**Comment by gnegrelli** [comment]
@andrewtavis I'll try a few other things before opening a PR.

**Comment by andrewtavis** [comment]
Great, @gnegrelli! Really looking forward to checking it out :) :)

**Comment by andrewtavis** [comment]
Reopening this @gnegrelli as there seems to be a problem with how the colors are being applied for the rectangular versions of the parliament plots now. Do you have an idea of where this might come from? You can see that the colors are off in the new version of the [plot example notebook](https://github.com/andrewtavis/poli-sci-kit/blob/main/examples/plot.ipynb). As soon as we get this figured out we'll be good to release 😊

**Comment by andrewtavis** [comment]
Maybe the order of the points got swapped at some point? It'd very weird.

**Comment by andrewtavis** [comment]
All good now, @gnegrelli 😊 30a67fb reverts the plotting method to the old one for the rectangle parliament plot. I'll update the readme with the new image given the new semicircle method and and send off v1.1.0 🚀

**Comment by andrewtavis** [comment]
Alright, we're all uploaded for `v1.1.0` @gnegrelli 😊 Thanks again for your support here! Great to have these improvements :) :)
