### ISSUE TITLE
Negative value on `seats_per_row`

### ISSUE THREAD

**Issue by gnegrelli** [andrewtavis/poli-sci-kit#30]
While testing some allocation cases for #20, I came across the following error.
```
ValueError: Number of samples, -1, must be non-negative.
```
Digging deeper, I noticed that one of the values in the `seats_per_row` was negative.

**Test case that replicates the error:**
```python
parliament(allocations=[2, 2, 8], num_rows=4)
```

**Comment by andrewtavis** [comment]
Hey @gnegrelli! Thanks for reporting :) Do we want to add something in to fix the row count if it's going to cause this error?

**Comment by gnegrelli** [comment]
I believe we can improve the error message so others can understand what caused the exception and how to avoid it.

**Comment by andrewtavis** [comment]
Sounds good, @gnegrelli! I'd happily merge in a PR for this as well :)

**Comment by andrewtavis** [comment]
Shall I assign?

**Comment by gnegrelli** [comment]
Sure!

**Comment by andrewtavis** [comment]
Awesome, @gnegrelli! Looking forward to the PR!

**Comment by andrewtavis** [comment]
b8baf22 does some minor refactoring for this, @gnegrelli :) Do you want to send along a quick test for the new exception here and then I can flesh out the example? You'd also be welcome to add the code that generated the plot you sent along in #20 to [plot.ipynb](https://github.com/andrewtavis/poli-sci-kit/blob/main/examples/plot.ipynb) if you're interested. As stated in the PR review, let's try to get `1.1.0` out by the end of the week 😊🚀

**Comment by andrewtavis** [comment]
bd01379 adds in the test, @gnegrelli :) We need to reopen #20 though as there seems to be a problem. Will explain in there.
